export const FETCH_DATA = 'FETCH_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'
export const FETCHING_DATA_PENDING = 'FETCHING_DATA_PENDING'
